apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: docker.io/battinahimaja/newimage:0.0.1.RELEASE
        ports:
        - containerPort: 8080
        env:
        - name: DOCKER_USERNAME
          value: Himaja.Battina@ibm.com
        - name: DOCKER_PASSWORD
          value: @HimajaBattina627281

